### ISSUE TITLE
Raider escort fighters shoot backward in second mission

### ISSUE THREAD

**Issue by nick87720z** [viewizard/astromenace#22] opened 2019-11-21 12:50 UTC
## Expected Behavior
In begining of second mission there is set of fighters, escorting cariers, initially facing towards player movement direction. At some distance from player they turn and begin to shoot in sequences of 3.

## Actual Behavior
Only for those, in escort (including final 6 after convoy deselerating) - first shot goes forward, but all next including two in first salvo go backward, this repeats for each escort fighter independently, not for entire escort. Attacking wave in the end doesn't have such problem. Don't remember is it case in later similar scenarios.

**Comment by viewizard** [comment] 2019-11-29 21:40
I reproduce this issue, will check what is wrong. Thanks!

**Comment by viewizard** [comment] 2019-11-30 11:40
I found the issue, previously enemy turrets and guns targeting code was merged (right before 1.4.0 release), and looks like I didn't test this properly (probably, because I kill this ships during testing before they start fire). So, first guns fire don't use targeting in ships code (we call it before ships code as soon, as fire trigger enabled), but as soon as targeting code "correct" fire direction vector, it fire backward.

I should think about best solution now.

**Comment by viewizard** [comment] 2019-11-30 12:07
So, usually, all enemy ships oriented to player with angles (x=0, y=-180, z=0) during creation, but in case of thous pirate ships, at the end of maneuver they have angles (x=-180, y=0, z=-180)... and this is the issue, since targeting code don't count on this now.

**Comment by nick87720z** [comment] 2019-11-30 12:59
Hm, is it different from scouring fighters, presenting on all factions (including fed allies)?

**Comment by viewizard** [comment] 2019-11-30 13:15
This affect on all ships that use ```rotz``` (rotation by z axis) in script.

**Closed** 2020-10-24 19:18 UTC
